# Generated by Django 5.0.6 on 2024-05-31 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_moves', models.CharField(max_length=1000)),
                ('player_black', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='chess_server.gamerequest')),
                ('player_white', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='chess_server.gamerequest')),
            ],
        ),
    ]
