# Generated by Django 5.0.6 on 2024-06-01 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_moves', models.CharField(max_length=1000)),
                ('white_move', models.BooleanField(default=True)),
                ('player_black', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_black', to='chess_server.gamerequest')),
                ('player_white', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_white', to='chess_server.gamerequest')),
            ],
        ),
    ]
